name: Experimental builds

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [non-ksu, ksu]

    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Clone kernel repo & prepare for compile
        run: |
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          cp ksumakefile.patch android_kernel_xiaomi_sm6150/
          cp umount.patch android_kernel_xiaomi_sm6150/
          cp compile.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/compile.sh

      - name: Patch kernel outside of compile script
        run: |
          cd android_kernel_xiaomi_sm6150/
          sed -i 's/CONFIG_IPC_LOGGING=y/# CONFIG_IPC_LOGGING is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_DEBUG_INFO=y/# CONFIG_DEBUG_INFO is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_PSTORE=y/# CONFIG_PSTORE is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_PSTORE_CONSOLE=y/# CONFIG_PSTORE_CONSOLE is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_PSTORE_PMSG=y/# CONFIG_PSTORE_PMSG is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_PSTORE_RAM=y/# CONFIG_PSTORE_RAM is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_ZRAM_WRITEBACK=y/# CONFIG_ZRAM_WRITEBACK is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_CC_STACKPROTECTOR_STRONG=y/CONFIG_CC_STACKPROTECTOR_REGULAR=y/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_HARDENED_USERCOPY=y/# CONFIG_HARDENED_USERCOPY is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_SLAB_FREELIST_RANDOM=y/# CONFIG_SLAB_FREELIST_RANDOM is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_SLAB_FREELIST_HARDENED=y/# CONFIG_SLAB_FREELIST_HARDENED is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/CONFIG_REFCOUNT_FULL=y/# CONFIG_REFCOUNT_FULL is not set/' arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          sed -i 's/KBUILD_CFLAGS\s\++= -O2/KBUILD_CFLAGS   += -O3/g' Makefile
          sed -i 's/LDFLAGS\s\++= -O2/LDFLAGS += -O3/g' Makefile
          cd ..

      - name: Compile kernel (${{ matrix.build-type }})
        run: |
          if [[ "${{ matrix.build-type }}" == "ksu" ]]; then
            cd android_kernel_xiaomi_sm6150/
            ./compile.sh --ksu --ln8000
            cd ..
          else
            cd android_kernel_xiaomi_sm6150/
            ./compile.sh --no-ksu --ln8000
            cd ..
          fi

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Clone AnyKernel3
        run: git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1

      - name: Copy kernel artifacts
        run: |
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          cd AnyKernel3

      - name: Upload artifacts (kernel)
        uses: actions/upload-artifact@v6
        with:
          name: "aosp-perf-neon-${{ matrix.build-type }}-experimental-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          path: |
            *.*

