name: Experimental builds

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [non-ksu, ksu]

    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Clone kernel repo & prepare for compile
        run: |
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          cp ksumakefile.patch android_kernel_xiaomi_sm6150/
          cp umount.patch android_kernel_xiaomi_sm6150/
          cp compile.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/compile.sh

      - name: Patch kernel outside of compile script
        run: |
          cd android_kernel_xiaomi_sm6150/
          wget -L "https://github.com/firelzrd/bore-scheduler/raw/refs/heads/main/patches/legacy/linux-4.19-bore/0001-linux4.19.y-bore5.1.0r2.patch" -O bore.patch
          patch -p1 < bore.patch
          cd ..

      - name: Compile kernel (${{ matrix.build-type }})
        run: |
          if [[ "${{ matrix.build-type }}" == "ksu" ]]; then
            cd android_kernel_xiaomi_sm6150/
            ./compile.sh --ksu --ln8000
            cd ..
          else
            cd android_kernel_xiaomi_sm6150/
            ./compile.sh --no-ksu --ln8000
            cd ..
          fi

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Clone AnyKernel3
        run: git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1

      - name: Copy kernel artifacts
        run: |
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          cd AnyKernel3

      - name: Upload artifacts (kernel)
        uses: actions/upload-artifact@v6
        with:
          name: "aosp-perf-neon-${{ matrix.build-type }}-experimental-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          path: |
            *.*

