name: Legacy builds

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [lineage-21]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing to compile (${{ matrix.build-type }})
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
            rm -rf android_kernel_xiaomi_sm6150
          fi
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-21
          cp build.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/build.sh

      - name: Compile the kernel (${{ matrix.build-type }})
        run: |
          cd android_kernel_xiaomi_sm6150/
          echo "Starting to compile..."
          ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_BLXX --f2fs=NONE
          cd ..

      - name: Preparing AnyKernel3 (${{ matrix.build-type }}, F2FS)
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          sed -i 's/supported.versions=11-16/supported.versions=11-14/' AnyKernel3/anykernel.sh

      - name: Zip kernel contents (${{ matrix.build-type }})
        run: |
          ZIPNAME="aosp-perf-neon-legacy-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*
          cd ..

      - name: Upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}-zip
          path: |
            *.zip
