name: Weekly builds

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [lineage-22-noksu, lineage-23-noksu, lineage-22-blxx, lineage-23-blxx, lineage-22-susfs, lineage-23-susfs]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing to compile (${{ matrix.build-type }}, F2FS)
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
            rm -rf android_kernel_xiaomi_sm6150
          fi
          if [[ "${{ matrix.build-type }}" == "lineage-22-noksu" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23-noksu" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          elif [[ "${{ matrix.build-type }}" == "lineage-22-blxx" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23-blxx" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          elif [[ "${{ matrix.build-type }}" == "lineage-22-susfs" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23-susfs" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          fi
          cp build.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/build.sh

      - name: Compile the kernel (${{ matrix.build-type }}, F2FS)
        run: |
          cd android_kernel_xiaomi_sm6150/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "lineage-22-noksu" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=NONE --f2fs=F2FS_TBYOOL
          elif [[ "${{ matrix.build-type }}" == "lineage-23-noksu" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=NONE --f2fs=F2FS_TBYOOL
          elif [[ "${{ matrix.build-type }}" == "lineage-22-blxx" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_BLXX --f2fs=F2FS_TBYOOL
          elif [[ "${{ matrix.build-type }}" == "lineage-23-blxx" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_BLXX --f2fs=F2FS_TBYOOL
          elif [[ "${{ matrix.build-type }}" == "lineage-22-susfs" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_VBAJ --f2fs=F2FS_TBYOOL
          elif [[ "${{ matrix.build-type }}" == "lineage-23-susfs" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_VBAJ --f2fs=F2FS_TBYOOL
          fi
          cd ..

      - name: Preparing AnyKernel3 (${{ matrix.build-type }}, F2FS)
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "lineage-22-noksu" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23-noksu" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-22-blxx" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23-blxx" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-22-susfs" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23-susfs" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          fi

      - name: Zip kernel contents (${{ matrix.build-type }}, F2FS)
        run: |
          ZIPNAME="aosp-perf-neon-f2fs_compression-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*
          cd ..

      - name: Preparing to compile (${{ matrix.build-type }}, No F2FS)
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
            rm -rf android_kernel_xiaomi_sm6150
          fi
          if [[ "${{ matrix.build-type }}" == "lineage-22-noksu" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23-noksu" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          elif [[ "${{ matrix.build-type }}" == "lineage-22-blxx" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23-blxx" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          elif [[ "${{ matrix.build-type }}" == "lineage-22-susfs" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23-susfs" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          fi
          cp build.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/build.sh

      - name: Compile the kernel (${{ matrix.build-type }}, No F2FS)
        run: |
          cd android_kernel_xiaomi_sm6150/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "lineage-22-noksu" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=NONE --f2fs=NONE
          elif [[ "${{ matrix.build-type }}" == "lineage-23-noksu" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=NONE --f2fs=NONE
          elif [[ "${{ matrix.build-type }}" == "lineage-22-blxx" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_BLXX --f2fs=NONE
          elif [[ "${{ matrix.build-type }}" == "lineage-23-blxx" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_BLXX --f2fs=NONE
          elif [[ "${{ matrix.build-type }}" == "lineage-22-susfs" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_VBAJ --f2fs=NONE
          elif [[ "${{ matrix.build-type }}" == "lineage-23-susfs" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_VBAJ --f2fs=NONE
          fi
          cd ..

      - name: Preparing AnyKernel3 (${{ matrix.build-type }}, No F2FS)
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "lineage-22-noksu" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23-noksu" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-22-blxx" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23-blxx" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-22-susfs" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23-susfs" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          fi

      - name: Zip kernel contents (${{ matrix.build-type }}, No F2FS)
        run: |
          ZIPNAME="aosp-perf-neon-none-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*
          cd ..

      - name: Upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}-zip
          path: |
            *.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded zips
        run: ls -lah artifacts

      - name: Timestamp
        id: ts
        run: |
          FANCYDATE=$(date +'%Y/%m/%d')
          echo "FANCYDATE=$FANCYDATE" >> $GITHUB_OUTPUT

      - name: Create Release and Upload builds
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: kernel-weekly-${{ needs.build.outputs.timestamp }}
          name: Weekly - ${{ steps.ts.outputs.FANCYDATE }}
          draft: false
          prerelease: false
          body: |
            > [!NOTE]
            > This build have integration with backslashxx's KernelSU & KernelSU-NEXT.   
            > KernelSU latest manager for backslashxx's KernelSU can be found in [here](https://github.com/backslashxx/KernelSU/releases).   
            > KernelSU latest manager for KernelSU-NEXT can be found in [here](https://t.me/ksunext_ci). 
               
            > [!WARNING]
            > KernelSU-NEXT variant includes SUSFS Version 2.0.0, meanwhile backslashxx's KernelSU does not include SUSFS.
            > KernelSU-NEXT uses backslashxx's scope-minimized hook v1.6, meanwhile backslashxx's KernelSU used hookless syscall table method.
            > Use the F2FS Compression ZIP if your ROM is using F2FS Compression.   
            > Use LineageOS 23 builds if you are on Android 16, for Android 15 and lower please use LineageOS 22 builds.

            > [!CAUTION]
            > Always backup your boot & dtbo image first before proceeding!
          files: |
            artifacts/lineage-22-noksu-zip/*.zip
            artifacts/lineage-23-noksu-zip/*.zip
            artifacts/lineage-22-blxx-zip/*.zip
            artifacts/lineage-23-blxx-zip/*.zip
            artifacts/lineage-22-susfs-zip/*.zip
            artifacts/lineage-23-susfs-zip/*.zip
          overwrite_files: true
