name: Weekly builds

on:
  workflow_dispatch:
  schedule:
    - cron: '5 5 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [lineage-20, lineage-21, lineage-22.2, lineage-23.0, lineage-23.1]

    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Prepare for compile (${{ matrix.build-type }})
        run: |
          if [[ "${{ matrix.build-type }}" == "lineage-20" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-20
          elif [[ "${{ matrix.build-type }}" == "lineage-21" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-21
          elif [[ "${{ matrix.build-type }}" == "lineage-22.2" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23.0" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          elif [[ "${{ matrix.build-type }}" == "lineage-23.1" ]]; then
            git clone https://github.com/xiaomi-sm6150/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.1
          fi
          cp ksumakefile.patch android_kernel_xiaomi_sm6150/
          cp umount.patch android_kernel_xiaomi_sm6150/
          cp compile.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/compile.sh

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_sm6150/
          ./compile.sh --ksu --ln8000
          cd ..

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Preparing AnyKernel3
        run: |
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "lineage-20" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=13/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-21" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=14/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-22.2" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23.0" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23.1" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          fi

      - name: Zip kernel contents
        run: |
          ZIPNAME="aosp-perf-neon-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}-zip
          path: |
            *.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded zips
        run: ls -lah artifacts

      - name: Create Release and Upload builds
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: kernel-${{ needs.build.outputs.timestamp }}
          name: Weekly build - ${{ needs.build.outputs.date }}
          draft: false
          prerelease: false
          body: |
            Notes:
              > Kernel has been built with -O3 optimization flag.   
              > Kernel has been built with ln8k charger imported.   
              > Lineage 23.1 build is following [xiaomi-sm6150]( https://github.com/xiaomi-sm6150/android_kernel_xiaomi_sm6150) instead of the official LineageOS repo. ⚠️   
              > KernelSU latest manager can be found in [here](https://t.me/ksunext_ci) or in [here](https://github.com/KernelSU-Next/KernelSU-Next/actions/workflows/build-manager-ci.yml).   
          files: |
            artifacts/lineage-20-zip/*.zip
            artifacts/lineage-21-zip/*.zip
            artifacts/lineage-22.2-zip/*.zip
            artifacts/lineage-23.0-zip/*.zip
            artifacts/lineage-23.1-zip/*.zip
          overwrite_files: true
