name: Testing

on:
  workflow_dispatch:
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [lineage-20, lineage-21, lineage-22.2, lineage-23.0]

    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Prepare for compile (${{ matrix.build-type }})
        run: |
          if [[ "${{ matrix.build-type }}" == "lineage-20" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-20
          elif [[ "${{ matrix.build-type }}" == "lineage-21" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-21
          elif [[ "${{ matrix.build-type }}" == "lineage-22.2" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "lineage-23.0" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.0
          fi
          cp ksumakefile.patch android_kernel_xiaomi_sm6150/
          cp compile.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/compile.sh

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_sm6150/
          wget -L https://github.com/tbyool/android_kernel_xiaomi_sm6150/commit/02baeab5aaf5319e5d68f2319516efed262533ea.patch -O f2fscompression.patch
          echo "CONFIG_F2FS_FS_COMPRESSION=y" >> arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          echo "CONFIG_F2FS_FS_LZ4=y" >> arch/arm64/configs/vendor/sdmsteppe-perf_defconfig
          patch -p1 < f2fscompression.patch
          ./compile.sh --ksu --ln8000
          cd ..

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Preparing AnyKernel3
        run: |
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "lineage-20" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=13/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-21" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=14/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-22.2" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "lineage-23.0" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=16/' AnyKernel3/anykernel.sh
          fi

      - name: Zip kernel contents
        run: |
          ZIPNAME="aosp-perf-neon-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}-zip
          path: |
            *.zip
