name: Testing

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [legacy, current]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing kernel sources
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
            rm -rf android_kernel_xiaomi_sm6150
          fi
          if [[ "${{ matrix.build-type }}" == "legacy" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-21
          elif [[ "${{ matrix.build-type }}" == "current" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150 --depth=1 -b lineage-23.2
          fi
          cp build.sh android_kernel_xiaomi_sm6150/
          chmod +x ./android_kernel_xiaomi_sm6150/build.sh

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_sm6150/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "legacy" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_NEXT --ln8k=TRUE
          elif [[ "${{ matrix.build-type }}" == "current" ]]; then
            ./build.sh sdmsteppe-perf_defconfig sweet.config --ksu=KSU_NEXT --ln8k=TRUE
          fi
          cd ..

      - name: Preparing AnyKernel3 sources
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "legacy" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-14/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "current" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
          fi

      - name: Pack & upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: perf-neon-sweet-testing-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}
          path: |
            AnyKernel3/*
